### ISSUE TITLE
Not able to decomile .class

### ISSUE THREAD

**Issue by tanishg** [dgileadi/vscode-java-decompiler#11]
You have written that "To see the decompiler in action, right-click on a Java symbol for which you don't have the source code, and choose Go to Definition (or simply command/ctrl+click on the symbol). You will see the decompiled code."
I do not find any java symbol..? could you please help me.

**Comment by dgileadi** [comment]
This extension does not open up individual .class or .jar files from your file system. To use this extension,

1. Create or open a Java project in VSCode and make sure it compiles successfully
2. Add an import in your pom.xml or build.gradle file to a jar for which you don't have the source code
3. Use one of the following methods to decompile a class:
    * Use Command+T or Ctrl+T (depending on your system) and type in the name of a class from that jar, or
    * In a .java file in your Java project, write some code that uses a class from that jar, and then right-click on that class name in your .java file and choose Go to Definition, or
    * In the Java Dependencies view of your Java project, browse to the jar and then the class you want to open, and click on it

The above only works within the context of a project that successfully compiles.
