### ISSUE TITLE
You cannot decompile a class by pressing Ctrl + T and then entering the class name.

### ISSUE THREAD

**Issue by liyuj** [dgileadi/vscode-java-decompiler#14]
You cannot decompile a class by pressing Ctrl + T and then entering the class name.
It was OK some time ago. It may be that there is incompatibility after the update of vscode.

**Comment by liyuj** [comment]
resolved.

**Comment by FeliciaAnnKelleyTaylorGV** [comment]
[<details><summary>Details</summary>](https://github.com/dgileadi/vscode-java-decompiler?tab=readme-ov-file#extension-settings)
<p>

<stdin> printf </stdin>

</p>
</details>
