### ISSUE TITLE
Support searching class to decompile in dependency from command palet

### ISSUE THREAD

**Issue by Merichbier** [dgileadi/vscode-java-decompiler#9]
Hi,

It would be really use useful to allow searching for a class to decompile (even class from dependencies) from the command pallet. Like the search do in Intellij.

I guess this one is a though one, but just wanted to through the idea here :)

Thanks for your work !

Cheers

**Comment by dgileadi** [comment]
Visual Studio Code supports opening any class in the classpath via [Ctrl+T (⌘T on Mac)](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name). If the class doesn't have source code then the decompiler will kick in. I use this all the time.

**Comment by Merichbier** [comment]
Damn how could I missed that! Thanks!
